[package]
name = "tiny-health-checker"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Mikusa <dmikusa@vmware.com>"]
description = "A tiny health checker for use in containers with Docker health checks"

[dependencies]
anyhow = "1.0"

[dependencies.ureq]
version = "2.4"
default-features = false